var obj1={
"result":[ {                                           //the thinker
	"language":"English",
		"key": "jha6SvVLXjU",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/The_Thinker%2C_Rodin.jpg/390px-The_Thinker%2C_Rodin.jpg",
		"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	},
{
	"language":"French",
		"key": "jha6SvVLXjU",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/The_Thinker%2C_Rodin.jpg/390px-The_Thinker%2C_Rodin.jpg",
	//	"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	"context":"Le Penseur est une sculpture en bronze d'Auguste Rodin, généralement placée sur un socle en pierre. Le travail montre une figure nue masculine de taille normale assise sur un rocher avec son menton reposant d'une main comme si profondément dans la pensée et est souvent utilisé comme image pour représenter la philosophie. Il ya environ 28 pièces coulées, dont le chiffre est d'environ 186 centimètres (73 po) de haut, mais pas tous ont été faites pendant la vie Rodin et sous sa supervision, Ainsi que diverses autres versions, plusieurs dans le plâtre, les études et les pièces moulées posthumes, dans une gamme de tailles. Rodin a d'abord conçu la figure dans le cadre d'une autre œuvre en 1880, mais le premier des pièces moulées en bronze monumental ne paraît pas avant 1904."
	

	},
	{
	"language":"German",
		"key": "jha6SvVLXjU",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/The_Thinker%2C_Rodin.jpg/390px-The_Thinker%2C_Rodin.jpg",
	//	"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	//"contextcontext":"Le Penseur est une sculpture en bronze d'Auguste Rodin, généralement placée sur un socle en pierre. Le travail montre une figure nue masculine de taille normale assise sur un rocher avec son menton reposant d'une main comme si profondément dans la pensée et est souvent utilisé comme image pour représenter la philosophie. Il ya environ 28 pièces coulées, dont le chiffre est d'environ 186 centimètres (73 po) de haut, mais pas tous ont été faites pendant la vie Rodin et sous sa supervision, Ainsi que diverses autres versions, plusieurs dans le plâtre, les études et les pièces moulées posthumes, dans une gamme de tailles. Rodin a d'abord conçu la figure dans le cadre d'une autre œuvre en 1880, mais le premier des pièces moulées en bronze monumental ne paraît pas avant 1904."
	"context":"Der Denker (französisch: Le Penseur) ist eine Bronzeskulptur von Auguste Rodin, die gewöhnlich auf einem Steinsockel platziert ist. Die Arbeit zeigt eine nackte männliche Figur von über Lebensgröße, die auf einem Felsen sitzt, wobei sein Kinn auf einer Hand wie in Gedanken versunken ist und oft als Bild zur Darstellung der Philosophie verwendet wird. Es gibt ungefähr 28 volle Größengussstücke, in denen die Zahl ungefähr 186 Zentimeter (73 Zoll) hoch ist, aber nicht alle wurden während Rodins Lebenszeit und unter seiner Aufsicht gemacht; Sowie verschiedene andere Versionen, mehrere in Gips, Studien und posthume Gussteile, in einer Reihe von Größen. Rodin konzipierte zuerst die Figur als Teil eines anderen Werkes im Jahre 1880, aber das erste der bekannten monumentalen Bronzegussstücke erschien erst 1904."

	},

	{
	"language":"Hindi",
		"key": "jha6SvVLXjU",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/The_Thinker%2C_Rodin.jpg/390px-The_Thinker%2C_Rodin.jpg",
	//	"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	//"contextcontext":"Le Penseur est une sculpture en bronze d'Auguste Rodin, généralement placée sur un socle en pierre. Le travail montre une figure nue masculine de taille normale assise sur un rocher avec son menton reposant d'une main comme si profondément dans la pensée et est souvent utilisé comme image pour représenter la philosophie. Il ya environ 28 pièces coulées, dont le chiffre est d'environ 186 centimètres (73 po) de haut, mais pas tous ont été faites pendant la vie Rodin et sous sa supervision, Ainsi que diverses autres versions, plusieurs dans le plâtre, les études et les pièces moulées posthumes, dans une gamme de tailles. Rodin a d'abord conçu la figure dans le cadre d'une autre œuvre en 1880, mais le premier des pièces moulées en bronze monumental ne paraît pas avant 1904."
	//"context":"Der Denker (französisch: Le Penseur) ist eine Bronzeskulptur von Auguste Rodin, die gewöhnlich auf einem Steinsockel platziert ist. Die Arbeit zeigt eine nackte männliche Figur von über Lebensgröße, die auf einem Felsen sitzt, wobei sein Kinn auf einer Hand wie in Gedanken versunken ist und oft als Bild zur Darstellung der Philosophie verwendet wird. Es gibt ungefähr 28 volle Größengussstücke, in denen die Zahl ungefähr 186 Zentimeter (73 Zoll) hoch ist, aber nicht alle wurden während Rodins Lebenszeit und unter seiner Aufsicht gemacht; Sowie verschiedene andere Versionen, mehrere in Gips, Studien und posthume Gussteile, in einer Reihe von Größen. Rodin konzipierte zuerst die Figur als Teil eines anderen Werkes im Jahre 1880, aber das erste der bekannten monumentalen Bronzegussstücke erschien erst 1904."
     "context":"द थिंकर (फ्रांसीसी: ले पिनेसुर) ऑगस्टी रॉडिन द्वारा एक कांस्य मूर्तिकला है, जिसे आमतौर पर एक पत्थर की कुरसी पर रखा जाता है। काम एक जीवन शैली के आकार का एक नग्न पुरूष व्यक्ति दिखाता है जिसमें एक चट्टान पर बैठे एक ठुढ़े पर बैठे एक हाथ पर आराम कर रहे हैं जैसे कि गहरी सोच में और अक्सर दर्शन के प्रतिनिधित्व करने के लिए छवि के रूप में प्रयोग किया जाता है। इसमें लगभग 28 पूर्ण आकार का कास्टिंग हैं, जिसमें यह आंकड़ा लगभग 186 सेंटीमीटर (73 इंच) ऊंचा है, हालांकि सभी को रॉडिन के जीवनकाल के दौरान और उनकी देखरेख में नहीं बनाया गया था; साथ ही साथ कई अन्य संस्करण, कई आकारों में, प्लास्टर, अध्ययन और मरणोपरांत कास्टिंग में कई। रॉडिन ने पहली बार 1880 में एक अन्य काम के रूप में आकृति की कल्पना की, लेकिन परिचित स्मारकीय कांस्य कास्टिंग के पहले 1 9 04 तक दिखाई नहीं दिया।"
	}]
	
};
use appdb;
db.Thethinker.insert(obj1);
db.Thethinker.find().pretty();